colav/Kahi_plugins

Kahi_ror_affiliations/kahi_ror_affiliations/Kahi_ror_affiliations.py, Kahi_ror_affiliations/kahi_ror_affiliations/_version.py
=> Added "source" key to the affiliations names list

Kahi_openalex_affiliations/kahi_openalex_affiliations/Kahi_openalex_affiliations.py
fixed error "pymongo.errors.AutoReconnect: localhost:27017: [Errno 24] Too many open files"
closing the client
=> [kahi_openalex_affiliations] fixed error

Kahi_openalex_works/kahi_openalex_works/Kahi_openalex_works.py
fix for error 
pymongo.errors.AutoReconnect: localhost:27017: [Errno 24] Too many open files
=> [Kahi_openalex_works] fixed error 

Kahi_openalex_sources/README.md, Kahi_openalex_sources/kahi_openalex_sources/Kahi_openalex_sources.py
* moved parallelization to threads
* fixes in mongo, called close in client
* fixed readme num_jobs is mandatory in the config file
=> Kahi openalex sources fixes

Kahi_scienti_affiliations/kahi_scienti_affiliations/Kahi_scienti_affiliations.py
The issue was solved by adding a function to check the format of some dates.
=> Added function to check the format of dates. issue #107

Kahi_staff_udea_affiliations/kahi_staff_udea_affiliations/Kahi_staff_udea_affiliations.py
fixed a typo that produced an error in issue #113
=> [Kahi_staff_udea_affiliations] fixed typo that produces error 

Kahi_openalex_works/README.md, Kahi_openalex_works/kahi_openalex_works/Kahi_openalex_works.py, Kahi_openalex_works/setup.py
Fixed errors on lang_poll function. Change the setup accordingly. Improve the readme since one of the libraries needs a C++ header. Forced the version of the dependencies.
=> Openalex works

Kahi_doaj_sources/README.md, Kahi_doaj_sources/kahi_doaj_sources/Kahi_doaj_sources.py
Added verbosity as a parameter, fixded minor error printing message. Update readme accordingly
Removed misleading print message
=> Doaj sources

Kahi_minciencias_opendata_person/kahi_minciencias_opendata_person/Kahi_minciencias_opendata_person.py
Fixed warning on assignment of a variable to a pandas series
=> Minciencias opendata person

Kahi_scopus_works/LICENSE, Kahi_scopus_works/MANIFEST.in, Kahi_scopus_works/README.md, Kahi_scopus_works/kahi_scopus_works/Kahi_scopus_works.py, Kahi_scopus_works/kahi_scopus_works/_version.py, Kahi_scopus_works/setup.py
Added lang_poll new libraries. Updated readme and setup accordingly. Improved messages through verbose variable. Improve error handling by adding math library function isnan
=> Scopus works

Kahi_ranking_udea_works/LICENSE, Kahi_ranking_udea_works/MANIFEST.in, Kahi_ranking_udea_works/README.md, Kahi_ranking_udea_works/kahi_ranking_udea_works/Kahi_ranking_udea_works.py, Kahi_ranking_udea_works/kahi_ranking_udea_works/_version.py, Kahi_ranking_udea_works/setup.py
Included support for issn sepparated by one or more spaces. More errors from the original file should be addressed by the provider.
=> Ranking udea works

Kahi_wos_works/kahi_wos_works/Kahi_wos_works.py
closed mongo client to avoid error too many open files
=> [Kahi_wos_works] error

Kahi_scholar_works/kahi_scholar_works/Kahi_scholar_works.py
added close in mongo client to avoid error too many open files
=> [Kahi_scholar_works] small fix

Kahi_elasticsearch_works/LICENSE, Kahi_elasticsearch_works/MANIFEST.in, Kahi_elasticsearch_works/README.md, Kahi_elasticsearch_works/kahi_elasticsearch_works/Kahi_elasticsearch_works.py, Kahi_elasticsearch_works/kahi_elasticsearch_works/_version.py, Kahi_elasticsearch_works/setup.py
Updated README
Fix error at the end of the execution
Added checking for nan
=> Elasticsearch works

Kahi_doaj_sources/kahi_doaj_sources/Kahi_doaj_sources.py, Kahi_openalex_sources/kahi_openalex_sources/Kahi_openalex_sources.py, Kahi_openalex_subjects/kahi_openalex_subjects/Kahi_openalex_subjects.py, Kahi_ror_affiliations/kahi_ror_affiliations/Kahi_ror_affiliations.py, Kahi_scienti_affiliations/kahi_scienti_affiliations/Kahi_scienti_affiliations.py, Kahi_scienti_person/kahi_scienti_person/Kahi_scienti_person.py, Kahi_scienti_sources/kahi_scienti_sources/Kahi_scienti_sources.py, Kahi_scopus_works/kahi_scopus_works/Kahi_scopus_works.py
The plugins were modified to create indexes in the source database.
=> Added indexes for the source database

Kahi_openalex_works/kahi_openalex_works/Kahi_openalex_works.py, Kahi_openalex_works/kahi_openalex_works/_version.py, Kahi_staff_udea_affiliations/kahi_staff_udea_affiliations/Kahi_staff_udea_affiliations.py, Kahi_staff_udea_affiliations/kahi_staff_udea_affiliations/_version.py
* fixed faculty error
* fixed key error
=> several fixes

Kahi_ranking_udea_works/kahi_ranking_udea_works/Kahi_ranking_udea_works.py, Kahi_ranking_udea_works/kahi_ranking_udea_works/_version.py, Kahi_scholar_works/kahi_scholar_works/Kahi_scholar_works.py, Kahi_scholar_works/kahi_scholar_works/_version.py, Kahi_scopus_works/kahi_scopus_works/Kahi_scopus_works.py, Kahi_scopus_works/kahi_scopus_works/_version.py, Kahi_wos_works/kahi_wos_works/Kahi_wos_works.py, Kahi_wos_works/kahi_wos_works/_version.py
Extraction of the mongodb connection for:
Kahi_ranking_udea_works
Kahi_scholar_works
Kahi_scopus_works
Kahi_wos_works
=> Extraction of the mongodb connection for some plugins

Kahi_impactu/setup.py
* updated versions for scienti_works and openalex_works
=> [Kahi_impactu] updating versions

Kahi_ranking_udea_works/kahi_ranking_udea_works/Kahi_ranking_udea_works.py, Kahi_ranking_udea_works/kahi_ranking_udea_works/_version.py, Kahi_scholar_works/kahi_scholar_works/Kahi_scholar_works.py, Kahi_scholar_works/kahi_scholar_works/_version.py, Kahi_scienti_works/kahi_scienti_works/Kahi_scienti_works.py, Kahi_scienti_works/kahi_scienti_works/_version.py, Kahi_scopus_works/kahi_scopus_works/Kahi_scopus_works.py, Kahi_scopus_works/kahi_scopus_works/_version.py, Kahi_wos_works/kahi_wos_works/Kahi_wos_works.py, Kahi_wos_works/kahi_wos_works/_version.py
Added doi processing to:
-Kahi_scienti_works
-Kahi_ranking_udea_works
-Kahi_scholar_works
-Kahi_scopus_works
-Kahi_wos_works
=> Added doi processing for some plugins

Kahi_scienti_affiliations/kahi_scienti_affiliations/Kahi_scienti_affiliations.py, Kahi_scienti_affiliations/kahi_scienti_affiliations/_version.py
=> fixed issue with group

Kahi_scholar_works/kahi_scholar_works/Kahi_scholar_works.py
fixed doi_processor calling doi
=> [Kahi_scholar_works] fixed error processing doi

Kahi_impactu/setup.py, Kahi_openalex_sources/kahi_openalex_sources/Kahi_openalex_sources.py, Kahi_openalex_sources/kahi_openalex_sources/_version.py
The following plugins are updated:
- Kahi
- Kahi_minciencias_opendata_person
- Kahi_openalex_person
- Kahi_openalex_works
- Kahi_ranking_udea_works
- Kahi_scholar_works
- Kahi_scienti_affiliations
- Kahi_scienti_person
- Kahi_scienti_sources
- Kahi_scienti_works
- Kahi_scopus_works
- Kahi_staff_udea_person
- Kahi_wos_works
=> [Kahi_impactu] updating plugins versions

Kahi_scienti_works/kahi_scienti_works/Kahi_scienti_works.py, Kahi_scienti_works/kahi_scienti_works/_version.py
I did this required change for the new release,
=> fixed doi processor

Kahi_scienti_works/README.md, Kahi_scienti_works/kahi_scienti_works/Kahi_scienti_works.py, Kahi_scienti_works/kahi_scienti_works/_version.py, Kahi_scienti_works/kahi_scienti_works/parser.py, Kahi_scienti_works/kahi_scienti_works/process_one.py
=> [kahi_scienti_works] working in no doi support

Kahi_openalex_works/README.md, Kahi_openalex_works/kahi_openalex_works/Kahi_openalex_works.py, Kahi_openalex_works/kahi_openalex_works/_version.py, Kahi_openalex_works/kahi_openalex_works/parser.py, Kahi_openalex_works/kahi_openalex_works/process_one.py, Kahi_openalex_works/setup.py, Kahi_scienti_works/README.md, Kahi_scienti_works/kahi_scienti_works/Kahi_scienti_works.py, Kahi_scienti_works/kahi_scienti_works/_version.py, Kahi_scienti_works/kahi_scienti_works/parser.py, Kahi_scienti_works/kahi_scienti_works/process_one.py, Kahi_scienti_works/setup.py, Kahi_staff_udea_person/kahi_staff_udea_person/Kahi_staff_udea_person.py, Kahi_staff_udea_person/kahi_staff_udea_person/_version.py
=> [kahi_openalex_works] working in similarity for no doi works

Kahi_openalex_works/setup.py, Kahi_scholar_works/kahi_scholar_works/Kahi_scholar_works.py, Kahi_scholar_works/kahi_scholar_works/_version.py, Kahi_scholar_works/kahi_scholar_works/parser.py, Kahi_scholar_works/kahi_scholar_works/process_one.py
* Implemented support to process works without doi using similarity (issue #245)
* Code divided to make it more readable
* Added documentation
=> [kahi_scholar_works] no doi support

Kahi_minciencias_opendata_works/LICENSE, Kahi_minciencias_opendata_works/MANIFEST.in, Kahi_minciencias_opendata_works/README.md, Kahi_minciencias_opendata_works/kahi_minciencias_opendata_works/Kahi_minciencias_opendata_works.py, Kahi_minciencias_opendata_works/kahi_minciencias_opendata_works/_version.py, Kahi_minciencias_opendata_works/kahi_minciencias_opendata_works/parser.py, Kahi_minciencias_opendata_works/kahi_minciencias_opendata_works/process_one.py, Kahi_minciencias_opendata_works/setup.py
This plugin that reads the information from minciencias opendata database to insert or update the information of the of academic products in colav's database.
=> [Kahi_minciencias_opendata_works] New plugin implemented for the minciencias opendata

Kahi_impactu_postcalculations/LICENSE, Kahi_impactu_postcalculations/MANIFEST.in, Kahi_impactu_postcalculations/README.md, Kahi_impactu_postcalculations/kahi_impactu_postcalculations/Kahi_impactu_postcalculations.py, Kahi_impactu_postcalculations/kahi_impactu_postcalculations/_version.py, Kahi_impactu_postcalculations/kahi_impactu_postcalculations/utils.py, Kahi_impactu_postcalculations/setup.py
Based on the code of @fedevergara  the plugin was rewritten
=> Calculations with fixes

Kahi_openalex_works/kahi_openalex_works/parser.py
required for https://github.com/colav/impactu/issues/17
=> [Kahi_openalex_works] implemented mathml parser

Kahi_openalex_works/kahi_openalex_works/parser.py, Kahi_openalex_works/setup.py, Kahi_scienti_works/kahi_scienti_works/parser.py
fixes issue https://github.com/colav/impactu/issues/53
=> fixes issue colav/impactu/issues/53

Kahi_scienti_person/kahi_scienti_person/Kahi_scienti_person.py
required for https://github.com/colav/impactu/issues/36
=> [kahi_scienti_person] normalized sex

Kahi_minciencias_opendata_person/kahi_minciencias_opendata_person/Kahi_minciencias_opendata_person.py
required for https://github.com/colav/impactu/issues/36
=> [kahi_minciencias_opendata_person] normalized sex

Kahi_minciencias_opendata_affiliations/kahi_minciencias_opendata_affiliations/Kahi_minciencias_opendata_affiliations.py, Kahi_minciencias_opendata_affiliations/kahi_minciencias_opendata_affiliations/_version.py, Kahi_minciencias_opendata_affiliations/setup.py
Modification of the plugin to consume group data directly from the yuku database.
=> [Kahi_minciencias_opendata_affiliations] Group data directly from yuku

Kahi_minciencias_opendata_works/kahi_minciencias_opendata_works/process_one.py
required for issue https://github.com/colav/impactu/issues/27
=> [kahi_minciencias_opendata_works] implemented groups in works directly

Kahi_scienti_works/kahi_scienti_works/parser.py, Kahi_scienti_works/kahi_scienti_works/process_one.py
implemented types with multiple levels issue https://github.com/colav/impactu/issues/65
=> [kahi_scienti_works] implemented types

Kahi_ranking_udea_works/kahi_ranking_udea_works/process_one.py
fix for issue https://github.com/colav/impactu/issues/68
failing in the elastic search code
=> [kahi_ranking_udea_works] fixed issue with source name

Kahi_minciencias_opendata_works/kahi_minciencias_opendata_works/parser.py, Kahi_openalex_works/kahi_openalex_works/parser.py, Kahi_scholar_works/kahi_scholar_works/parser.py
required for issue https://github.com/colav/impactu/issues/69
=> fixed level in types

Kahi_minciencias_opendata_person/README.md, Kahi_minciencias_opendata_person/kahi_minciencias_opendata_person/Kahi_minciencias_opendata_person.py, Kahi_minciencias_opendata_person/kahi_minciencias_opendata_person/_version.py, Kahi_scienti_person/kahi_scienti_person/Kahi_scienti_person.py
Solved https://github.com/colav/impactu/issues/66
=> [Kahi_minciencias_opendata_person] The plugin is transformed to use Yuku

Kahi_scienti_works/kahi_scienti_works/_version.py, Kahi_scienti_works/kahi_scienti_works/process_one.py
implemented https://github.com/colav/Kahi_plugins/issues/279
=> [kahi_scienti_works] implemented author_others

Kahi_ranking_udea_works/kahi_ranking_udea_works/_version.py, Kahi_ranking_udea_works/kahi_ranking_udea_works/parser.py
required for issue https://github.com/colav/impactu/issues/53
=> [kahi_ranking_udea_works] fixed title quality

Kahi_openalex_person/README.md, Kahi_openalex_person/kahi_openalex_person/Kahi_openalex_person.py, Kahi_openalex_person/kahi_openalex_person/_version.py
required for https://github.com/colav/impactu/issues/73  and https://github.com/colav/impactu/issues/14
=> [kahi_openalex_person] added related works

Kahi_scienti_person/kahi_scienti_person/Kahi_scienti_person.py
Required for issues:
- https://github.com/colav/impactu/issues/14
- https://github.com/colav/impactu/issues/4
=> ["Kahi_scienti_person"] Related works to the authors were added

Kahi_minciencias_opendata_person/kahi_minciencias_opendata_person/Kahi_minciencias_opendata_person.py, Kahi_minciencias_opendata_works/kahi_minciencias_opendata_works/process_one.py
Required for the issues:
- https://github.com/colav/impactu/issues/4
- https://github.com/colav/impactu/issues/14
=> [Kahi_minciencias_opendata_person] Product ids in related_works are adjusted

Kahi_wikidata_affiliations/LICENSE, Kahi_wikidata_affiliations/MANIFEST.in, Kahi_wikidata_affiliations/README.md, Kahi_wikidata_affiliations/kahi_wikidata_affiliations/Kahi_wikidata_affiliations.py, Kahi_wikidata_affiliations/kahi_wikidata_affiliations/_version.py, Kahi_wikidata_affiliations/setup.py
created wikidata plugin to get titles ad logos from the wikidata dump
required for issue https://github.com/colav/impactu/issues/70
=> [Kahi_wikidata_affiliations]

Kahi_wikidata_affiliations/kahi_wikidata_affiliations/Kahi_wikidata_affiliations.py
required for https://github.com/colav/impactu/issues/70
=> [kahi_wikidata_affiliations] added provenance to logo

Kahi_scienti_works/kahi_scienti_works/parser.py, Kahi_scienti_works/kahi_scienti_works/process_one.py
fixed issue https://github.com/colav/impactu/issues/72
=> implemented issue https://github.com/colav/impactu/issues/72

Kahi_authors_unicity/LICENSE, Kahi_authors_unicity/MANIFEST.in, Kahi_authors_unicity/README.md, Kahi_authors_unicity/kahi_authors_unicity/Kahi_authors_unicity.py, Kahi_authors_unicity/kahi_authors_unicity/_version.py, Kahi_authors_unicity/setup.py, Kahi_minciencias_opendata_person/kahi_minciencias_opendata_person/Kahi_minciencias_opendata_person.py
The implementation of this plugin is oriented to solve the issues:
-https://github.com/colav/impactu/issues/4
-https://github.com/colav/impactu/issues/14
=> [Kahi_authors_unicity] Plugin implemented to address unicity of Authors.

Kahi_post_person_work_cleaning/LICENSE, Kahi_post_person_work_cleaning/MANIFEST.in, Kahi_post_person_work_cleaning/README.md, Kahi_post_person_work_cleaning/kahi_post_person_work_cleaning/Kahi_post_person_work_cleaning.py, Kahi_post_person_work_cleaning/kahi_post_person_work_cleaning/_version.py, Kahi_post_person_work_cleaning/setup.py
issue https://github.com/colav/impactu/issues/141
=> [Kahi_post_person_work_cleaning] implemented plugin for cleaning works not belong to person.

Kahi_authors_unicity/kahi_authors_unicity/Kahi_authors_unicity.py, Kahi_openalex_person/kahi_openalex_person/Kahi_openalex_person.py
* https://github.com/colav/impactu/issues/175
=> fixed issue https://github.com/colav/impactu/issues/175

Kahi_minciencias_opendata_works/kahi_minciencias_opendata_works/parser.py, Kahi_minciencias_opendata_works/kahi_minciencias_opendata_works/process_one.py
These improvements repair the isuues: 
-https://github.com/colav/impactu/issues/144
-https://github.com/colav/impactu/issues/188
=> Adding minciencias author to the work authors list

Kahi_impactu_post_cites_count/kahi_impactu_post_cites_count/Kahi_impactu_post_cites_count.py, Kahi_impactu_post_cites_count/kahi_impactu_post_cites_count/_version.py
* issue https://github.com/colav/impactu/issues/200
=> [Kahi_impactu_post_cites_count] Fixed citations_count for person collection

Kahi_authors_unicity/README.md, Kahi_authors_unicity/kahi_authors_unicity/Kahi_authors_unicity.py, Kahi_elasticsearch_works/kahi_elasticsearch_works/Kahi_elasticsearch_works.py, Kahi_minciencias_opendata_works/kahi_minciencias_opendata_works/parser.py, Kahi_openalex_person/kahi_openalex_person/Kahi_openalex_person.py, Kahi_openalex_works/kahi_openalex_works/Kahi_openalex_works.py, Kahi_openalex_works/kahi_openalex_works/parser.py, Kahi_openalex_works/kahi_openalex_works/process_one.py, Kahi_scholar_person/kahi_scholar_person/parser.py, Kahi_scienti_person/kahi_scienti_person/Kahi_scienti_person.py, Kahi_scienti_works/kahi_scienti_works/Kahi_scienti_works.py, Kahi_scienti_works/kahi_scienti_works/process_one.py, Kahi_staff_person/kahi_staff_person/Kahi_staff_person.py
- https://github.com/colav/impactu/issues/181
- https://github.com/colav/impactu/issues/183 
- https://github.com/colav/impactu/issues/177
- https://github.com/colav/impactu/issues/185
- https://github.com/colav/impactu/issues/188
=> several issues

Kahi_scienti_works/kahi_scienti_works/process_one.py
This fix solve the issue https://github.com/colav/impactu/issues/96
=> [Kahi_scienti_works] Fixed doi '5' value error

Kahi_minciencias_opendata_works/kahi_minciencias_opendata_works/process_one.py
This fix solves part of author assignment with scienti id, from issue: https://github.com/colav/impactu/issues/110
=> [Kahi_minciencias_opendata_works] Fixed correct author assignment

Kahi_minciencias_opendata_person/kahi_minciencias_opendata_person/Kahi_minciencias_opendata_person.py, Kahi_minciencias_opendata_works/kahi_minciencias_opendata_works/Kahi_minciencias_opendata_works.py, Kahi_minciencias_opendata_works/kahi_minciencias_opendata_works/process_one.py
https://github.com/colav/impactu/issues/261
* [Kahi_minciencias_opendata_person] support to add all authors
* kahi_minciecias_opendata_works (para todos los productos que no son eventos, patentes o proyectos)
=> new Minciencias data

Kahi_openalex_works/kahi_openalex_works/parser.py, Kahi_openalex_works/kahi_openalex_works/process_one.py, Kahi_ranking_udea_works/kahi_ranking_udea_works/parser.py, Kahi_scholar_works/kahi_scholar_works/parser.py, Kahi_scienti_works/kahi_scienti_works/parser.py
issue https://github.com/colav/impactu/issues/278
=> several fueatures

Kahi_staff_affiliations/kahi_staff_affiliations/Kahi_staff_affiliations.py, Kahi_staff_person/kahi_staff_person/Kahi_staff_person.py
- https://github.com/colav/impactu/issues/339
- https://github.com/colav/impactu/issues/355
=> [Kahi_staff_person, Kahi_staff_affiliations] update to receive new data

Kahi_impactu_postcalculations/kahi_impactu_postcalculations/indexes.py
https://github.com/colav/impactu/issues/418
=> [Kahi_impactu_postcalculations] implemented index required 

Kahi_minciencias_opendata_works/kahi_minciencias_opendata_works/process_one.py
- https://github.com/colav/impactu/issues/469
- https://github.com/colav/impactu/issues/470
=> [Kahi_minciencias_opendata_works] Changes to process DAM oriented works

Kahi_scienti_person/kahi_scienti_person/Kahi_scienti_person.py, Kahi_scienti_works/kahi_scienti_works/parser.py, Kahi_scienti_works/kahi_scienti_works/process_one.py
Related issue:
- https://github.com/colav/impactu/issues/387
- https://github.com/colav/impactu/issues/470
=> [Kahi_scienti_works, Kahi_scienti_person] Changes to process oriented works

Kahi_impactu_postcalculations/README.md, Kahi_impactu_postcalculations/kahi_impactu_postcalculations/Kahi_impactu_postcalculations.py, Kahi_impactu_postcalculations/kahi_impactu_postcalculations/topics.py, Kahi_openalex_works/kahi_openalex_works/parser.py
* [Kahi_openalex_works] added topics to works, required by https://github.com/colav/impactu/issues/417
* requires https://github.com/colav/Kahi/pull/15
=> working in topics

Kahi_scholar_person/kahi_scholar_person/process_one.py
Related issue:
- https://github.com/colav/impactu/issues/464
=> [Kahi_scholar_person] Fixed error in the search for authors

Kahi_openalex_person/kahi_openalex_person/Kahi_openalex_person.py
[kahi_openalex_person] implemented split_names https://github.com/colav/impactu/issues/487#issuecomment-2807481974
=> serveral issues

Kahi_orcid_person/kahi_orcid_person/Kahi_orcid_person.py
- https://github.com/colav/impactu/issues/451
=> [Kahi_orcid_person] scienti rule is added for registration update

Kahi_openalex_person/kahi_openalex_person/Kahi_openalex_person.py
- https://github.com/colav/impactu/issues/451
=> [Kahi_openalex_person] Added feature to update records

Kahi_scienti_sources/kahi_scienti_sources/Kahi_scienti_sources.py
- https://github.com/colav/impactu/issues/490#issuecomment-2816925292
=> [Kahi_scienti_sources] Book editorials are integrated as sources

Kahi_minciencias_opendata_works/kahi_minciencias_opendata_works/process_one.py, Kahi_scienti_works/kahi_scienti_works/parser.py
- https://github.com/colav/impactu/issues/507
=> [Kahi_minciencias_opendata_works, Kahi_scienti_works] fixed the update of the ranking field

Kahi_scienti_person/kahi_scienti_person/Kahi_scienti_person.py
se prioriza staff frente a scienti, para que los nombres sean de mejor caildad
=> [Kahi_scienti_person] fixed prioritization of author name fields

Kahi_scimago_sources/kahi_scimago_sources/Kahi_scimago_sources.py
Related issue:
- https://github.com/colav/impactu/issues/503
=> [Kahi_scimago_sources] Fixed updated field

Kahi_orcid_person/README.md, Kahi_orcid_person/kahi_orcid_person/Kahi_orcid_person.py
Related isuue:
- https://github.com/colav/impactu/issues/526
=> [Kahi_orcid_person] plugin improvement with split_name_part

Kahi_impactu_post_cites_count/kahi_impactu_post_cites_count/Kahi_impactu_post_cites_count.py
Related issue:
- https://github.com/colav/impactu/issues/609
- https://github.com/colav/impactu/issues/588
=> [Kahi_impactu_post_cites_count] The counts for citations and products has been added for sources
